### ISSUE TITLE
Combining printed numbers

### ISSUE THREAD

**Issue by agdamsbo** [HannahJohns/rankinPlot#1]
Hi. My colleague was using your package, and asked if there was an option to print counts and percentage on the bars. Like [REVASCT 1-year follow-up](https://doi.org/10.1016/S1474-4422(17)30047-9).

I wrote a small extension to your function to include a "n (percentage)" option for the ´printNumbers´ parameter and added ´textWeight´ parameter for ´fontface´ in ´geom_text()´.

``` r
remotes::install_github("agdamsbo/rankinPlot")
#> Skipping install of 'rankinPlot' from a github remote, the SHA1 (df75a419) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(rankinPlot)
df <- alteplase
x <- table(mRS = df$mRS-1, Group = df$treat)
grottaBar(
  x,
  groupName = "Group",
  scoreName = "mRS",
  colourScheme = "custom",
  textWeight = "italic",
  printNumbers = "n (percentage)"
) + viridis::scale_fill_viridis(discrete = TRUE, direction = -1)
```

![](https://i.imgur.com/2tayobB.png)

<sup>Created on 2023-01-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'll create a pull-request if you like.

**Comment by agdamsbo** [comment]
Ok. The missing contrast bothered me. I think I came up with a solution to that in the fork as well.

``` r
remotes::install_github("agdamsbo/rankinPlot")
#> Skipping install of 'rankinPlot' from a github remote, the SHA1 (47a57178) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(ggplot2)
library(rankinPlot)
df <- alteplase
x <- table(mRS=df$mRS,Group=df$treat)
     
      grottaBar(x,groupName="Group",
              scoreName = "mRS",
              colourScheme ="custom",
              textWeight = "italic",
              textColor = c("black","white"),
              textCut = 5,
              printNumbers = "n (percentage)"
     ) + viridis::scale_fill_viridis(discrete = TRUE,direction = -1) 
```

![](https://i.imgur.com/KmOMfM0.png)

<sup>Created on 2023-01-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Very much inspired from here: https://stackoverflow.com/a/47281431/21019325

**Comment by HannahJohns** [comment]
Thanks for this, these changes are both great. I'll merge them into the main repository

**Comment by HannahJohns** [comment]
Changes have been added to the repository. I modified the new argument names to fit with the existing structure. The new version has been submitted to CRAN and should be available for download soon
